-- Restore test_cases table and populate it
-- Run this in Supabase SQL Editor

-- 1. Create the table if it's missing
CREATE TABLE IF NOT EXISTS test_cases (
  id bigint generated by default as identity primary key,
  problem_id bigint references problems on delete cascade not null,
  input text not null,
  expected_output text not null,
  is_sample boolean default false,
  order_index integer default 0
);

-- 2. Populate test cases from the sample input/output in problems table
-- This ensures every problem has at least one test case to run against
INSERT INTO test_cases (problem_id, input, expected_output, is_sample)
SELECT id, sample_input, sample_output, true
FROM problems
WHERE NOT EXISTS (
    SELECT 1 FROM test_cases WHERE test_cases.problem_id = problems.id
);

-- 3. Verify the count
SELECT count(*) as total_test_cases FROM test_cases;
