-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Public user data linked to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  email text,
  rating integer default 1200,
  problems_solved integer default 0,
  country text,
  organization text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROBLEMS
create table problems (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  difficulty text not null check (difficulty in ('EASY', 'MEDIUM', 'HARD')),
  tags text[] default '{}',
  acceptance_rate numeric(5,2) default 0,
  input_format text,
  output_format text,
  constraints text,
  sample_input text,
  sample_output text,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEST CASES
create table test_cases (
  id bigint generated by default as identity primary key,
  problem_id bigint references problems on delete cascade not null,
  input text not null,
  expected_output text not null,
  is_sample boolean default false,
  order_index integer default 0
);

-- SUBMISSIONS
create table submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  problem_id bigint references problems on delete cascade not null,
  code text not null,
  language text not null,
  status text not null, -- ACCEPTED, WRONG_ANSWER, etc.
  execution_time integer, -- in ms
  memory_used integer, -- in KB
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES

-- Profiles: Public read, User update own
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Problems: Public read
alter table problems enable row level security;
create policy "Problems are viewable by everyone" on problems for select using (true);

-- Submissions: User read own, User insert own
alter table submissions enable row level security;
create policy "Users can view own submissions" on submissions for select using (auth.uid() = user_id);
create policy "Users can insert own submissions" on submissions for insert with check (auth.uid() = user_id);

-- TRIGGER: Create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- AUDIT LOGS (Persistent, append-only admin logs with before/after diffs)
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_id text not null,
  actor_username text not null,
  action varchar(100) not null,
  entity_type varchar(100) not null,
  entity_id text not null,
  before_state text,
  after_state text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  reason varchar(500),
  correlation_id varchar(100)
);

create index if not exists idx_audit_logs_timestamp on audit_logs(timestamp);
create index if not exists idx_audit_logs_actor_id on audit_logs(actor_id);
create index if not exists idx_audit_logs_action on audit_logs(action);
create index if not exists idx_audit_logs_entity_type on audit_logs(entity_type);
create index if not exists idx_audit_logs_entity_id on audit_logs(entity_id);

alter table audit_logs enable row level security;
-- Only service_role or admins can read audit logs directly via Supabase REST
create policy "Admins and service role can view audit logs" on audit_logs
  for select using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

-- OPERATIONAL INCIDENTS & HEALTH ALERTS
create table if not exists incidents (
  id bigint generated by default as identity primary key,
  incident_key varchar(100) not null,
  title varchar(255) not null,
  description text,
  component varchar(100) not null,
  severity varchar(50) not null default 'WARNING',
  status varchar(50) not null default 'OPEN',
  first_seen_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_seen_at timestamp with time zone default timezone('utc'::text, now()) not null,
  occurrence_count integer default 1 not null,
  acknowledged_at timestamp with time zone,
  acknowledged_by varchar(100),
  resolved_at timestamp with time zone,
  resolved_by varchar(100),
  resolution_note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_incidents_key on incidents(incident_key);
create index if not exists idx_incidents_status on incidents(status);
create index if not exists idx_incidents_severity on incidents(severity);
create index if not exists idx_incidents_last_seen on incidents(last_seen_at);

alter table incidents enable row level security;
create policy "Admins and service role can view incidents" on incidents
  for select using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

-- SEED DATA (Sample Problems)
insert into problems (title, description, difficulty, tags, acceptance_rate, sample_input, sample_output) values
('Two Sum', 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.', 'EASY', ARRAY['Array', 'Hash Table'], 49.2, 'nums = [2,7,11,15], target = 9', '[0,1]'),
('Add Two Numbers', 'You are given two non-empty linked lists representing two non-negative integers. Add the two numbers and return the sum as a linked list.', 'MEDIUM', ARRAY['Linked List', 'Math'], 38.5, 'l1 = [2,4,3], l2 = [5,6,4]', '[7,0,8]'),
('Median of Two Sorted Arrays', 'Given two sorted arrays nums1 and nums2, return the median of the two sorted arrays.', 'HARD', ARRAY['Binary Search'], 35.2, 'nums1 = [1,3], nums2 = [2]', '2.0');
