-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Public user data linked to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  email text,
  rating integer default 1200,
  problems_solved integer default 0,
  country text,
  organization text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- PROBLEMS
create table problems (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  difficulty text not null check (difficulty in ('EASY', 'MEDIUM', 'HARD')),
  tags text[] default '{}',
  acceptance_rate numeric(5,2) default 0,
  input_format text,
  output_format text,
  constraints text,
  sample_input text,
  sample_output text,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- TEST CASES
create table test_cases (
  id bigint generated by default as identity primary key,
  problem_id bigint references problems on delete cascade not null,
  input text not null,
  expected_output text not null,
  is_sample boolean default false,
  order_index integer default 0
);

-- SUBMISSIONS
create table submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  problem_id bigint references problems on delete cascade not null,
  code text not null,
  language text not null,
  status text not null, -- ACCEPTED, WRONG_ANSWER, etc.
  execution_time integer, -- in ms
  memory_used integer, -- in KB
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES

-- Profiles: Public read, User update own
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Problems: Public read
alter table problems enable row level security;
create policy "Problems are viewable by everyone" on problems for select using (true);

-- Submissions: User read own, User insert own
alter table submissions enable row level security;
create policy "Users can view own submissions" on submissions for select using (auth.uid() = user_id);
create policy "Users can insert own submissions" on submissions for insert with check (auth.uid() = user_id);

-- TRIGGER: Create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- SEED DATA (Sample Problems)
insert into problems (title, description, difficulty, tags, acceptance_rate, sample_input, sample_output) values
('Two Sum', 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.', 'EASY', ARRAY['Array', 'Hash Table'], 49.2, 'nums = [2,7,11,15], target = 9', '[0,1]'),
('Add Two Numbers', 'You are given two non-empty linked lists representing two non-negative integers. Add the two numbers and return the sum as a linked list.', 'MEDIUM', ARRAY['Linked List', 'Math'], 38.5, 'l1 = [2,4,3], l2 = [5,6,4]', '[7,0,8]'),
('Median of Two Sorted Arrays', 'Given two sorted arrays nums1 and nums2, return the median of the two sorted arrays.', 'HARD', ARRAY['Binary Search'], 35.2, 'nums1 = [1,3], nums2 = [2]', '2.0');
